<?php
/**
 * Created by PhpStorm.
 * User: thib
 * Date: 24/10/17
 * Time: 14:32
 */

namespace App\Service;


class Router extends \Core\Service\Router
{

    private $dic;

    public function __construct(\Core\Service\DIC $dic){
        $this->setDIC($dic);
    }

    public function execute($uri)
    {
        try{
            return parent::execute($uri); // TODO: Change the autogenerated stub
        }catch(\Exception $e){
            $controller = $this->getDIC()->get('Controller\Blog');
            $controller->notFound();
        }
    }

    public function getDIC(){
        return $this->dic;
    }

    public function setDIC(\Core\Service\DIC $dic){
        $this->dic = $dic;
    }
}